### ISSUE TITLE
Extremely Slow on High Speed Internet Connection (Win10)

### ISSUE THREAD

**Issue by danucalovj** [justcoding121/Titanium-Web-Proxy#575]
Using the default code in the README, no response modification/injection, etc., and decryption SSL (e.DecryptSSL = True).

Internet Connection: Cox 1 Gbps Fiber

No Proxy - Testing via Speedtest.net
Down: 701.30 Mbps
Up: 729.69 Mbps

**w/TWP Proxy - Testing via Speedtest.net**
Down 8.29
Up: 12.14

w/Charles Web Debugging Proxy (3rd Party Product + SSL Inspection Enabled)
Down: 618.43 Mbps
Up: 604.77

Based on the above, I don't think PC specs have anything to do with the issue since I'm running a comparison with another software-based proxy (Charles Web Debugging Proxy). Begs the question of why the major discrepancy in speed between the two?

Any ideas what could be causing this?

**Comment by danucalovj** [comment]
Other details:

When running TWP, and going to something like MSN.com where there's quite a few simultaneous requests/responses coming through, CPU utilization spikes all the way up to 85% utilization with an average of 45%.

Conversely, running Charles Web Debugging Proxy, and doing the same test, CPU utilization never reaches above 20% and stays at an average of 8%.

PC Specs:
OS Name	Microsoft Windows 10 Pro
Version	10.0.17763 Build 17763
Processor	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 4001 Mhz, 4 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM)	32.0 GB

**Comment by harrip12** [comment]
I have the same issue on some of the machines. On start of Titanium Proxy initially it takes too much time to process first request.

**Comment by StephaneGraziano** [comment]
I sent a PR yesterday #574 (already alive) and this morning #576 
It should resolve all the speed issues, let me know if it's ok :)

**Comment by justcoding121** [comment]
I am not an expert in performance tuning, and I don't have much free time to look into the issues. But any experimental changes and contributions are welcome.

@StephaneGraziano 
Okay. What about buffer size for the client connection. Do you think that needs to be changed as well?
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/src/Titanium.Web.Proxy/ProxyServer.cs#L777

Also your change for thread pool I merged yesterday, Why was async completion port threads not increased, was that intended?
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/src/Titanium.Web.Proxy/ProxyServer.cs#L762

**Comment by danucalovj** [comment]
@StephanieGraziano I saw that PR, #574, it definitely improved page load times significantly especially on first page request on a busy website, but did not improve overall performance. Still getting roughly 8Mbps download speed on a 1Gbps connection. I'll try #576 this morning and will report back.

**Comment by justcoding121** [comment]
My google performance test on Chrome consistantly shows the opposite on the latest master with two merges. :-) I don't understand the internal mechanics.

**Test without this Proxy**

![image](https://user-images.githubusercontent.com/2637679/55638687-c3e7c200-5795-11e9-8019-fb420df282b9.png)

**Test with this Proxy**

![image](https://user-images.githubusercontent.com/2637679/55638591-8edb6f80-5795-11e9-9b1a-c0ebca8c84c2.png)

**Comment by danucalovj** [comment]
I can confirm now that with #576 the issue is corrected! Awesome job @StephaneGraziano 

Getting nearly full speeds compared to without the proxy.

Issue resolved. Closing issue.

**Comment by justcoding121** [comment]
Thanks @StephaneGraziano

**Comment by justcoding121** [comment]
After reading the ms article, I feel increasing thread size on the thread pool as more requests come in may not be a good solution. We should find blocking calls in our code that perhaps is causing thread starvation using the _perfView_ tool.

https://blogs.msdn.microsoft.com/vancem/2018/10/16/diagnosing-net-core-threadpool-starvation-with-perfview-why-my-service-is-not-saturating-all-cores-or-seems-to-stall/

**Comment by StephaneGraziano** [comment]
The code is blocking at SSLStream.AuthenticateAsServer/Client because these methods call the Stream.Read method instead of ReadAsync and it’s very hard to rewrite SSLStream... tuning ThreadPool is not an elegant solution but it’s ok for heavy loads.
BTW there’s no perf increase to change client ReadBufferSize but it’s ok to remove it.
For thread pool I didn’t find code which change completion port and changing working thread is enough on my side.

**Comment by justcoding121** [comment]
Okay. So if a sync block is happening outside the code that we can control I dont see any other option other than firing new threads per request. But I am not dure why the call is named as AuthenticateClientAsync if its blocking internally. Hope MS will fix it ib future .net releases.

**Comment by danucalovj** [comment]
Should I keep this issue open until the above is worked through?

**Comment by justcoding121** [comment]
Yes. Lets leave it open.

**Comment by StephaneGraziano** [comment]
With my last PR :
https://github.com/justcoding121/Titanium-Web-Proxy/pull/578
https://github.com/justcoding121/Stream-Extended/pull/44

I think it's time to close the issue.

**Comment by justcoding121** [comment]
Thanks again for your work! This can be closed now.
